### ISSUE TITLE
v0.3 feedback

### ISSUE THREAD

**Issue by jeffryhartanto** [CS2103AUG2016-F09-C2/main#61]
# Developer Guide
-  Are you retaining the same architecture as Address book? If not your Figure 1 should be updated to reflect the changes and similar to other diagrams.
- Your explanation for `delete` command must match its sequence diagram diagram. e.g. `delete 1` and `delete 3`.
- Try to fill all third column of User Stories.
- There shouldn't be any diagram in the Use Case, see Use Case 8 and so on. Put them around `delete` sequence diagram.
- Similarly, you can explain other interesting design decisions you made, if any.

# User Guide
- I still prefer combining `recur` command to `add`. However, you can decide it with your teammates. Start dog-fooding the app, so you may know which one is better. 
- The `Command summary` section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.

**Comment by eugenepeh** [comment]
Suanzhi please do the following

# Developer Guide
- Your explanation for delete command must match its sequence diagram diagram. e.g. delete 1 and delete 3.
- Try to fill all third column of User Stories.
- There shouldn't be any diagram in the Use Case, see Use Case 8 and so on. Put them around delete sequence diagram.
- Similarly, you can explain other interesting design decisions you made, if any.

Junwen please do the following
# User Guide
- The Command summary section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.

**Comment by jeffryhartanto** [comment]
Take a look at this [handout](https://docs.google.com/document/d/1kAth-pTOzwCJFVjS6KU8O50bCvijDqpb6GsOyJTD0Ds/pub?embedded=true) if you haven't done so. I think you miss some points.
